### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by NazikSoft** [maxml/social-network-signin#2]
I think will be great, if logout posible use in another activity. For example, I have LoginActitvity with SignInManager fot init lib, if I want use logout in another Actitvity (MainActitvity's button logout) I need instance of manager.

**Comment by maxml** [comment]
SignInManager is already written as Singleton. 
As you use SignInManager in Application class, you can use it for logout.

More details here - https://github.com/maxml/social-network-signin/blob/master/social-signin/src/main/java/com/maxml/socialsignin/SignInManager.java#L29
