### ISSUE TITLE
Facebook connect

### ISSUE THREAD

**Issue by NazikSoft** [maxml/social-network-signin#4]
I found a little bug with registration in Facebook API, you need write your SHA1 in API console, when I use Facebook SDK first time all is right, but next time I catch error, it's look like Android studio (?) generate new SHA key that it not registered in Fasebook API. 

Some info from stackoverflow:
https://stackoverflow.com/questions/23674131/android-facebook-integration-invalid-key-hash

**Comment by maxml** [comment]
@NazikSoft can you provide some example for this situation? Maybe some snippet?...

**Comment by maxml** [comment]
Use 0.2.1 version. Usage - https://github.com/maxml/social-network-signin/blob/master/app/src/main/java/com/maxml/socialsignin/demo/MainActivity.java#L73
